main:
  - name: "Tour"
    url: "tour"
    weight: 10
  - name: "News"
    url: "news"
    weight: 20
  - name: "People"
    url: "people"
    weight: 30
  - name: "Research"
    url: "research"
    weight: 80
  - name: "Publications"
    url: "publication"
    weight: 50
  - name: "Projects"
    url: "projects"
    weight: 70
  - name: "RF-Sensing"
    url: "RF-Sensing"
    weight: 90
  - name: "Contact"
    url: "contact"
    weight: 60
