main:
  - name: "Home"
    url: "tour"
    weight: 10
  - name: "News"
    url: "news"
    weight: 20
  - name: "People"
    url: "people"
    weight: 30
  - name: "Projects"
    identifier: "projects"
    url: "projects"
    weight: 40
  - name: "Publications"
    url: "publication"
    weight: 50
  - name: "Contact"
    url: "contact"
    weight: 60
